//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace note2_ex.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class muti_langLocal_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal muti_langLocal_aspx() {
            
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("note2_ex.App_LocalResources.muti_langLocal.aspx", typeof(muti_langLocal_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 按鈕一的文字(ENG Default) 的當地語系化字串。
        /// </summary>
        internal static string Button1Res_Text {
            get {
                return ResourceManager.GetString("Button1Res.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 按鈕一經過時會浮現的文字(ENG Default) 的當地語系化字串。
        /// </summary>
        internal static string Button1Res_ToolTip {
            get {
                return ResourceManager.GetString("Button1Res.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Label1的文字(ENG Default) 的當地語系化字串。
        /// </summary>
        internal static string Label1Res_Text {
            get {
                return ResourceManager.GetString("Label1Res.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Label1經過時會浮現的文字(ENG Default) 的當地語系化字串。
        /// </summary>
        internal static string Label1Res_ToolTip {
            get {
                return ResourceManager.GetString("Label1Res.ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Kate(ENG Default) 的當地語系化字串。
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這一頁的頁簽(ENG Default) 的當地語系化字串。
        /// </summary>
        internal static string Page_Title {
            get {
                return ResourceManager.GetString("Page.Title", resourceCulture);
            }
        }
    }
}
